--[[
	******************************************************************************
	* @name			:	management
	* @authors		:	Cod2rDude
	* @date			:	December 31 2025
	* @lastEdit		:	January 6 2025
	* @brief		:	A package for managing tasks on server.
	* @version		:	0.0.6
	******************************************************************************
	* @attention
	*
	* Copyright © 2025 Axon Corporation.
	* All rights reserved.
	*
	* This software is licensed under terms that can be found in the LICENSE file
	* in the root directory of this software component.
	* If no LICENSE file comes with this software, it is provided AS-IS.
	*
	******************************************************************************
--]]

--management.src.__index
return require(script.__main__)